obs space:
  name: insitu_profile_bathy
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_profile_bathy.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_profile_bathy.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: InsituTemperature
obs error:
  covariance model: diagonal

#--------------------------------------------------------------------------------------
#                   START OF OBS FILTERS
# The QC filters used here are based on the document by IODE that can be found at
# https://cdn.ioos.noaa.gov/media/2017/12/recommendations_in_situ_data_real_time_qc.pdf
#--------------------------------------------------------------------------------------
obs filters:

  # Land Check
  - filter: Domain Check
    where:
    - variable: {name: GeoVaLs/sea_area_fraction}
      minvalue: 0.5
#--------------------------------------------------------------------------------------
## Filters for T:
#--------------------------------------------------------------------------------------
  #------------------------------------------------------------------------------------
  ### Global range test
  #------------------------------------------------------------------------------------
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: -2.5
    maxvalue: 40.0

  #------------------------------------------------------------------------------------
  ### Regional range tests
  #------------------------------------------------------------------------------------
  
  #### Red Sea
  #------------------------------------------------------------------------------------
  ####
  #### the document linked here describes Red sea as the are between 10N, 40E;
  #### 20N, 50E; 30N, 30E; 10N, 40E. But that would also include Gulf of Aden.
  #### A more reasonable choice seemed to be a box that extends from 10 N to
  #### 30 N and 30 E to 45 East .
  #------------------------------------------------------------------------------------
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: 21.7
    maxvalue: 40.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 10
      maxvalue: 30
    - variable:
        name: MetaData/longitude
      minvalue: 30

  #### Mediterranean Sea
  #-----------------------------------------------------------------------------
  ##### Area 1/3 for Mediterranean Sea
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: 10.0
    maxvalue: 40.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 30
      maxvalue: 40
    - variable:
        name: MetaData/longitude
      minvalue: -6
      maxvalue: 40
  ##### Area 2/3 for Mediterranean Sea
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: 10.0
    maxvalue: 40.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 40
      maxvalue: 41.5
    - variable:
        name: MetaData/longitude
      minvalue: 20
      maxvalue: 30
  ##### Area 3/3 for Mediterranean Sea
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: 10.0
    maxvalue: 40.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 40
      maxvalue: 46
    - variable:
        name: MetaData/longitude
      minvalue: 0
      maxvalue: 20

  #### Northwestern shelves
  #-----------------------------------------------------------------------------
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: -2.0
    maxvalue: 24.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 50
      maxvalue: 60
    - variable:
        name: MetaData/longitude
      minvalue: -20
      maxvalue: 10
  #### Southwestern shelves
  #-----------------------------------------------------------------------------
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: -2.0
    maxvalue: 30
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 25
      maxvalue: 50
    - variable:
        name: MetaData/longitude
      minvalue: -30
      maxvalue: 0

  #### Arctic Sea
  #-----------------------------------------------------------------------------
  - filter: Bounds Check
    filter variables: [{name: waterTemperature}]
    minvalue: -1.92
    maxvalue: 25.0
    where:
    - variable:
        name: MetaData/latitude
      minvalue: 60

  - filter: Background Check
    filter variables: [{name: waterTemperature}]
    threshold: 5.0
    absolute threshold: 5.0

