observations:
- obs space:
    name: sss_smap
    obsproc subdir: SSS
    obsproc regex: SMAP_L2B_SSS_NRT_?????_[AD]_????????T??????.h5
    provider: SMAP
    output file: sss_smap.ioda.nc
- obs space:
    name: sss_smos
    provider: SMOS
    obsproc subdir: SSS
    output file: sss_smos.ioda.nc
    obsproc regex: SM_OPER_MIR_OSUDP2_????????T??????_????????T??????_700_001_1.nc
- obs space:
    name: adt_3b_egm2008
    obsproc subdir: ADT
    obsproc regex: rads_adt_3b_???????.nc
    provider: RADS
    output file: adt_all.nc4
- obs space:
    name: icec_amsr2_north
    provider: AMSR2
    obsproc subdir: icec
    output file: icec_amsr2_north_1.ioda.nc
    obsproc regex: AMSR2-SEAICE-NH_v2r2_GW1_s???????????????_e???????????????_c???????????????.nc
