observations:
- obs space:
    name: sss_smap
    obsproc subdir: SSS
    obsproc regex: SMAP_L2B_SSS_NRT_?????_[AD]_????????T??????.h5
    provider: SMAP
    output file: sss_smap.ioda.nc
- obs space:
    name: sss_smos
    provider: SMOS
    obsproc subdir: SSS
    output file: sss_smos.ioda.nc
    obsproc regex: SM_OPER_MIR_OSUDP2_????????T??????_????????T??????_700_001_1.nc
- obs space:
    name: adt_3b_egm2008
    obsproc subdir: ADT
    obsproc regex: rads_adt_3b_???????.nc
    provider: RADS
    output file: rads_adt_3b_2021181.ioda.nc

