observations:
- obs space:
    name: sss_smap
    obsproc subdir: SSS
    obsproc regex: SMAP_L2B_SSS_NRT_?????_[AD]_????????T??????.h5
    provider: SMAP
    output file: sss_smap.ioda.nc
- obs space:
    name: sss_smos
    provider: SMOS
    obsproc subdir: SSS
    output file: sss_smos.ioda.nc
    obsproc regex: SM_OPER_MIR_OSUDP2_????????T??????_????????T??????_700_001_1.nc
- obs space:
    name: adt_rads_all
    obsproc subdir: ADT
    obsproc regex: rads_adt_??_???????.nc
    provider: RADS
    output file: adt_rads_all.nc4
- obs space:
    name: icec_amsr2_north
    provider: AMSR2
    obsproc subdir: icec
    output file: icec_amsr2_north.ioda.nc
    obsproc regex: AMSR2-SEAICE-NH_v2r2_GW1_s???????????????_e???????????????_c???????????????.nc
- obs space:
    name: icec_amsr2_south
    provider: AMSR2
    obsproc subdir: icec
    output file: icec_amsr2_south.ioda.nc
    obsproc regex: AMSR2-SEAICE-NH_v2r2_GW1_s???????????????_e???????????????_c???????????????.nc
- obs space:
    name: sst_metopb_l3u
    provider: GHRSST
    obsproc subdir: 'sst'
    output file: sst_metopb_l3u.ioda.nc
    obsproc regex: '??????????????-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc'
    bounds:
      units: C
      min: -3.0
      max: 50.0
