observations:
- obs space:
    name: sss_smap
    obsproc subdir: 'SSS'
    obsproc regex: sss_smap_?.nc4
    provider: SMAP
    output file: sss_smap.ioda.nc
- obs space:
    name: sss_smos
    provider: SMOS
    obsproc subdir: 'SSS'
    output file: sss_smos.ioda.nc
    obsproc regex: sss_smos_?.nc4
- obs space:
    name: adt_3b_egm2008
    obsproc subdir: 'ADT'
    obsproc regex: rads_adt_??_???????.nc4
    provider: RADS
    output file: adt_all.nc4
- obs space:
    name: icec_amsr2_north
    provider: AMSR2
    obsproc subdir: 'ice'
    output file: icec_amsr2_north.ioda.nc
    obsproc regex: icec_amsr2_north_?.nc4
- obs space:
    name: sst_metopb_l3u_so025
    provider: GHRSST
    obsproc subdir: 'sst'
    output file: sst_metopb_l3u_so025.ioda.nc
    obsproc regex: '??????????????-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc'
    bounds:
      units: C
      min: -3.0
      max: 50.0
