obs space:
  name: adt_j2
  get values:
    time interpolation: linear
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}adt_j2.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/adt_j3.${PDY}${cyc}.nc4
  simulated variables: [absoluteDynamicTopography]
get values:
  time interpolation: linear
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
