obs space:
  name: temp_profile_glider
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}temp_profile_glider.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/temp_profile_glider.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: InsituTemperature

obs error:
  covariance model: diagonal

obs filters:
  # Passivate obs where ocean fraction is > 90%
  - filter: Domain Check
    action:
      name: passivate
    where:
    - variable: {name: GeoVaLs/sea_area_fraction}
      maxvalue: 0.9

