machine: hera

job options:
  job-name: gsivar
  account: da-cpu
  qos: debug
  partition: hera
  time: '30:00'
  nodes: 4
  tasks-per-node: 24
  cpus-per-task: 1
  mem: 96Gb

directories:
  HOMEgfs: /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test
  STAGEDIR: /scratch2/NCEPDEV/stmp1/Russ.Treadon/STAGEDIR/gsi/gdasanal_00
  RUNDIR: /scratch1/NCEPDEV/stmp2/Russ.Treadon/RUNDIRS/gsi_anl_00

app files:
  APPEXE: /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/exec/gsi.x
  APPYML: /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/sorc/gdas.cd/ush/ufoeval/gsiparm.anl
  runscript: rungsi.sh
