machine: hera

job options:
  account: da-cpu
  qos: debug
  partition: hera
  time: '30:00'
  nodes: 4
  tasks-per-node: 24
  cpus-per-task: 1
  mem: 96Gb

directories:
  HOMEgfs: /scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/test
  STAGEDIR: /scratch3/NCEPDEV/da/Russ.Treadon/STAGEDIR
  RUNDIR: /scratch3/NCEPDEV/stmp2/Russ.Treadon/RUNDIRS

app files:
  DA_CORE: jedi
  DA_TYPE: 3dv
  APPEXE: /scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/exec/gdas.x
  INCEXE: /scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/exec/fv3jedi_fv3inc.x
