obs space:
  name: viirs_n20_aod
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}viirs_n20.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/diag_viirs_n20_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [aerosol_optical_depth]
  channels: 4 
get values:
  interpolation method: barycentric
obs operator:
  name: AodCRTM
  Absorbers: [H2O,O3]
  obs options:
    Sensor_ID: v.viirs-m_j1 
    EndianType: little_endian
    CoefficientPath: !ENV ${DATA}/crtm/
    AerosolOption: aerosols_gocart_default
obs error:
  covariance model: diagonal 
