obs space:
  name: viirs_npp_aod
  obsdatain:
    obsfile: $(OBS_DIR)/$(OBS_PREFIX)viirs_npp.$(OBS_DATE).nc4
  obsdataout:
    obsfile: $(DIAG_DIR)/diag_viirs_npp_$(OBS_DATE).nc4
  io pool:
    max pool size: 1
  simulated variables: [aerosol_optical_depth]
  channels: 4 
get values:
  interpolation method: $(INTERP_METHOD)
obs operator:
  name: AodCRTM
  Absorbers: [H2O,O3]
  Clouds: [Water, Ice]
  Cloud_Fraction: 1.0
  obs options:
    Sensor_ID: v.viirs-m_npp
    EndianType: little_endian
    CoefficientPath: $(CRTM_COEFF_DIR)/
    AerosolOption: aerosols_gocart_default
obs error:
  covariance model: diagonal 
