obs operator:
  name: GnssroBndNBAM
  obs options:
    use_compress: 1
    sr_steps: 2
    vertlayer: full
    super_ref_qc: NBAM
obs space:
  name: gnssrobndnbam
  distribution:
    name: Halo
    halo size: 1250e3
  obsdatain:
    engine:
      type: H5File
      obsfile: $(DATA)/obs/$(OPREFIX)gnssro.tm00.bufr_d.nc
#    obsgrouping:
#      group variables: [ 'sequenceNumber' ]
#      sort variable: 'impactHeightRO'
#      sort order: 'ascending'
  obsdataout:
    engine:
      type: H5File
      obsfile: $(DATA)/diags/diag_gnssro_{{ current_cycle | to_YMDH }}.nc
  simulated variables: [bendingAngle]

obs filters:
# Apply gross check using pccf
# Step 0-A: Create Diagnostic Flags 
# Diagnostic flag for pccf
- filter: Create Diagnostic Flags
  filter variables:  
  - name: bendingAngle 
  flags:
  - name: pccfCheckReject
    initial value: false 
    force reinitialization: true

# Diagnostic flag for qfro
- filter: Create Diagnostic Flags
  filter variables:
  - name: bendingAngle
  flags:
  - name: qfroCheckReject
    initial value: false
    force reinitialization: true

# Step 0-B: pccf Check - good: 0.1-100, reject: 0
- filter: Bounds Check
  filter variables:
  - name: bendingAngle
  where:
  - variable:
      name: MetaData/satelliteIdentifier
    is_in: 265-269,750-755,44,786,820,825
  test variables:
  - name: MetaData/pccf
  minvalue: 0.1
  maxvalue: 100.1
  actions:
    - name: set
      flag: pccfCheckReject
    - name: reject

# Step 0-B: qfro Check - good: 0, reject: 1
- filter: Bounds Check
- filter: RejectList
  filter variables:
  - name: bendingAngle
  where:
  - variable:
      name: MetaData/satelliteIdentifier
    is_in: 3-5,421,440,821
  test variables:
  - name: MetaData/qualityFlags
  minvalue: -0.1
  maxvalue: 0.1
  actions:
    - name: set
      flag: qfroCheckReject
    - name: reject

#1. gpstop
- filter: Domain Check
  filter variables:
  - name: bendingAngle
  where:
  - variable:
      name: MetaData/impactHeightRO
    minvalue: 0
    maxvalue: 55000.1
  action:
    name: reject
#2. commgpstop
- filter: Bounds Check
  filter variables:
  - name: bendingAngle
  where:
  - variable:
      name: MetaData/satelliteIdentifier
    is_in: 265,266,267,268,269
  test variables:
  - name: MetaData/impactHeightRO
  maxvalue: 45000.1
  action:
    name: reject
#3. metop below 8 km
- filter: Bounds Check
  filter variables:
  - name: bendingAngle
  where:
  - variable:
      name: MetaData/satelliteIdentifier
    is_in: 3-5
  test variables:
  - name: MetaData/impactHeightRO
  minvalue: 8000.1
  action:
    name: reject
#4. assign obs error 
- filter: ROobserror
  filter variables:
  - name: bendingAngle
  errmodel: NBAM
#5. RONBAM cut off check
- filter: Background Check RONBAM
  filter variables:
  - name: bendingAngle
#6. Obs error inflate
- filter: Background Check RONBAM
  filter variables:
  - name: bendingAngle
  action:
    name: RONBAMErrInflate
#7. Background check
#- filter: Background Check
#  filter variables:
#  - name: bendingAngle
#  threshold: 10
#  action:
#    name: reject
obs localizations:
- localization method: Horizontal Gaspari-Cohn
  lengthscale: 1250e3
  max nobs: 10000
