obs space:
  name: amsua_n19
  distribution:
    name: Halo
    halo size: 1250e3
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ./obs/${OPREFIX}amsua_n19.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ./diags/diag_amsua_n19_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [brightnessTemperature]
  channels: &amsua_n19_channels 4-6,9-14
obs operator:
  name: CRTM
  Absorbers: [H2O,O3]
  Clouds: [Water, Ice]
  Cloud_Fraction: 1.0
  obs options:
    Sensor_ID: amsua_n19
    EndianType: little_endian
    CoefficientPath: ./crtm/
obs error:
  covariance model: diagonal
obs filters:
- filter: Bounds Check
  filter variables:
  - name: brightnessTemperature
    channels: *amsua_n19_channels
  minvalue: 100.0
  maxvalue: 500.0
  action:
    name: reject
#  Gross check
- filter: Background Check
  filter variables:
  - name: brightnessTemperature
    channels: *amsua_n19_channels
  threshold: 3.0
  action:
    name: reject
obs localizations:
- localization method: Horizontal Gaspari-Cohn
  lengthscale: 1250e3
  max nobs: 10000
