obs space:
  name: amsua_n19
  distribution:
    name: Halo
    halo size: 1250e3
  obsdatain:
    engine:
      name: H5File
      obsfile: $(OBS_DIR)/$(OBS_PREFIX)amsua_n19.$(OBS_DATE).nc4
  obsdataout:
    engine:
      name: H5File
      obsfile: $(DIAG_DIR)/diag_amsua_n19_lgetkf.$(OBS_DATE).nc4
  io pool:
    max pool size: 1
  simulated variables: [brightness_temperature]
  channels: 4-6,9-14
obs operator:
  name: CRTM
  Absorbers: [H2O,O3]
#   Clouds: [Water, Ice]
#   Cloud_Fraction: 1.0
  obs options:
    Sensor_ID: amsua_n19
    EndianType: little_endian
    CoefficientPath: crtm/
obs error:
  covariance model: diagonal
obs filters:
- filter: Bounds Check
  filter variables:
  - name: brightness_temperature
    channels: 4-6,9-14
  minvalue: 100.0
  maxvalue: 500.0
- filter: Background Check
  filter variables:
  - name: brightness_temperature
    channels: 4-6,9-14
  threshold: 3.0
- filter: Domain Check
  filter variables:
  - name: brightness_temperature
    channels: 4-6,9-14
  where:
  - variable:
      name: scan_position@MetaData
    minvalue: 4
    maxvalue: 27
  - variable:
      name: brightness_temperature_1@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
  - variable:
      name: brightness_temperature_2@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
  - variable:
      name: brightness_temperature_3@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
  - variable:
      name: brightness_temperature_4@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
  - variable:
      name: brightness_temperature_6@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
  - variable:
      name: brightness_temperature_15@ObsValue
    minvalue: 50.0
    maxvalue: 550.0
obs localizations:
- localization method: Horizontal Gaspari-Cohn
  lengthscale: 1250e3
  max nobs: 10000
