obs space:
  name: sondes
  distribution:
    name: Halo
    halo size: 1250e3
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ./obs/${OPREFIX}sondes.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ./diags/diag_sondes_lgetkf_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [windEastward, windNorthward, airTemperature]
obs operator:
  name: VertInterp
obs error:
  covariance model: diagonal
obs filters:
- filter: PreQC
  maxvalue: 3
- filter: Background Check
  filter variables:
  - name: windEastward
  - name: windNorthward
  - name: airTemperature
  threshold: 2.0
obs localizations:
- localization method: Horizontal Gaspari-Cohn
  lengthscale: 1250e3
  max nobs: 10000
