obs space:
  name: sondes
  distribution:
    name: Halo
    halo size: 1250e3
  obsdatain:
    engine:
      name: H5File
      obsfile: $(OBS_DIR)/$(OBS_PREFIX)sondes.$(OBS_DATE).nc4
  obsdataout:
    engine:
      name: H5File
      obsfile: $(DIAG_DIR)/diag_sondes_lgetkf.$(OBS_DATE).nc4
  io pool:
    max pool size: 1
  simulated variables: [eastward_wind, northward_wind, air_temperature]
obs operator:
  name: VertInterp
obs error:
  covariance model: diagonal
obs filters:
- filter: PreQC
  maxvalue: 3
- filter: Background Check
  filter variables:
  - name: eastward_wind
  - name: northward_wind
  - name: air_temperature
  threshold: 2.0
obs localizations:
- localization method: Horizontal Gaspari-Cohn
  lengthscale: 1250e3
  max nobs: 10000
