obs space:
  name: omi_aura
  obsdatain:
    engine:
      type: H5File
      obsfile: {{ DATA }}/obs/{{ OPREFIX }}omi_aura.${{ current_cycle | to_YMDH }}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: {{ DATA }}/diags/diag_omi_aura_${{ current_cycle | to_YMDH }}.nc4
  io pool:
    max pool size: 1
  simulated variables: [ozoneTotal]

obs operator:
  name: AtmVertInterpLay
  geovals: [mole_fraction_of_ozone_in_air]
  coefficients: [0.007886131] # convert from ppmv to DU
  nlevels: [1]

obs pre filters:
- filter: Perform Action
  filter variables:
  - name: ozoneTotal
  action:
    name: assign error
    error parameter: 6.0

obs prior filters:
# GSI read routine QC
# range sanity check
- filter: Bounds Check
  filter variables:
  - name: ozoneTotal
  minvalue: 0
  maxvalue: 10000
  action:
    name: reject

# Do not use the data if row anomaly (bit 10)is 1
- filter: RejectList
  filter variables:
  - name: ozoneTotal
  where:
  - variable:
      name: MetaData/totalOzoneQualityFlag
    any_bit_set_of: 9 

# Scan position check: reject scan position >= 25
- filter: RejectList
  filter variables:
  - name: ozoneTotal
  where:
  - variable:
      name: MetaData/sensorScanPosition
    minvalue: 25

# Accept total_ozone_error_flag values of 0 and 1, but not any others.
- filter: RejectList 
  filter variables:
  - name: ozoneTotal
  where:
  - variable:
      name: MetaData/totalOzoneQualityCode
    is_not_in: 0, 1

# Use data with best ozone algorighm
- filter: RejectList
  filter variables:
  - name: ozoneTotal
  where:
  - variable:
      name: MetaData/bestOzoneAlgorithmFlag
    is_in: 3, 13

obs post filters:
# GSI setup routine QC
# Gross check
- filter: Background Check
  filter variables:
  - name: ozoneTotal
  threshold: 10.0
  absolute threshold: 300.0
  action:
    name: reject

# End of Filters


