obs space:
  name: omi_aura
  obsdatain:
    engine:
      type: H5File
      obsfile: $(DATA)/obs/$(OPREFIX)omi_aura.${{ current_cycle | to_YMDH }}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: $(DATA)/diags/diag_omi_aura_${{ current_cycle | to_YMDH }}.nc4
  io pool:
    max pool size: 1
  simulated variables: [ozoneTotal]
obs operator:
  name: AtmVertInterpLay
  geovals: [ozoneLayer]
  coefficients: [0.007886131] # convert from ppmv to DU
  nlevels: [1]
