obs space:
  name: omi_aura
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}omi_aura.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/diag_omi_aura_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [integrated_layer_ozone_in_air]
obs operator:
  name: AtmVertInterpLay
  geovals: [mole_fraction_of_ozone_in_air]
  coefficients: [0.007886131] # convert from ppmv to DU
  nlevels: [1]
