obs space:
  name: sfc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sfc.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/diag_sfc_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [stationPressure]
obs operator:
  name: SfcPCorrected
  da_psfc_scheme: GSI
  geovar_sfc_geomz: surface_geometric_height
  geovar_geomz: geopotential_height
linear obs operator:
  name: Identity
