obs space:
  name: sfcship
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sfcship.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      overwrite: true
      obsfile: !ENV ${DATA}/diags/diag_sfcship_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [surface_pressure, air_temperature, specific_humidity]
obs operator:
  name: Composite
  components:
    - name: VertInterp
      variables:
      - name: air_temperature
      - name: specific_humidity
    - name: SfcPCorrected
      variables:
      - name: surface_pressure
      da_psfc_scheme: GSI
      geovar_sfc_geomz: surface_geopotential_height
      geovar_geomz: geopotential_height
linear obs operator:
  name: Identity

obs filters:
  # Observation range sanity check
  - filter: Bounds Check
    filter variables:
    - name: surface_pressure
    minvalue: 37499.0
    maxvalue: 106999.0
    action:
      name: reject
    filter variables:
    - name: air_temperature
    minvalue: 195.0
    maxvalue: 327.0
    action:
      name: reject
    filter variables:
    - name: specific_humidity
    minvalue: 0.0
    maxvalue: 0.03499
    action:
      name: reject

  # Gross error check with (O - B) / ObsError greater than threshold.
  - filter: Background Check
    filter variables:
    - name: surface_pressure
    threshold: 3.6
    absolute threshold: 990.0
    action:
      name: reject
    defer to post: true
    filter variables:
    - name: air_temperature
    threshold: 7.0
    absolute threshold: 9.0
    action:
      name: reject
    defer to post: true

  # Reject all ObsType 183
  - filter: BlackList
    where:
    - variable:
        name: surface_pressure@ObsType
      is_in: 183
