obs space:
  name: sfcship
  obsdatain:
    obsfile: $(OBS_DIR)/$(OBS_PREFIX)sfcship.$(OBS_DATE).nc4
  obsdataout:
    obsfile: $(DIAG_DIR)/diag_sfcship_$(OBS_DATE).nc4
  io pool:
    max pool size: 1
  simulated variables: [eastward_wind, northward_wind, air_temperature, specific_humidity, surface_pressure]
get values:
  interpolation method: $(INTERP_METHOD)
#
obs operator:
  name: Composite
  components:
   - name: GSISfcModel
     use_fact10: true
     variables:
     - name: air_temperature
     - name: specific_humidity
     - name: eastward_wind
     - name: northward_wind
   - name: SfcPCorrected
     variables:
     - name: surface_pressure
     da_psfc_scheme: UKMO
#
obs filters:
  # Observation Range Sanity Check
  - filter: Bounds Check
    filter variables:
    - name: surface_pressure
    minvalue: 37499
    maxvalue: 106999
    action:
      name: reject 
  #
  - filter: Bounds Check
    filter variables:
    - name: air_temperature
    minvalue: 195
    maxvalue: 327
    action:
      name: reject
  #
  - filter: Bounds Check
    filter variables:
    - name: specific_humidity
    minvalue: 1.0E-7
    maxvalue: 0.034999999
    action:
      name: reject
  #
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    minvalue: -130
    maxvalue: 130
    action:
      name: reject
  #
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    test variables:
    - name: Velocity@ObsFunction
    maxvalue: 130.0
    action:
      name: reject
  # Reject when difference of wind direction is more than 50 degrees.
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    test variables:
    - name: WindDirAngleDiff@ObsFunction
      options:
        minimum_uv: 3.5
    maxvalue: 50.0
    action:
      name: reject
  # Reject all obs with PreQC mark already set above 3
  # - filter: PreQC
  #   maxvalue: 3
  #   action:
  #     name: reject
  # Assign obsError.
  - filter: Perform Action
    filter variables:
    - name: surface_pressure
    action:
      name: assign error
      error parameter: 130             # 130 Pa (1.3mb)
  #
  - filter: Perform Action
    filter variables:
    - name: surface_pressure
    action:
      name: assign error
      error function:
        name: ObsErrorModelStepwiseLinear@ObsFunction
        options:
          xvar:
            name: ObsValue/surface_pressure
          xvals: [92000, 85000, 70000]
          errors: [130, 150, 190]
  #
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    action:
      name: assign error
      error parameter: 1.4             # 1.4 m/s
  #
  - filter: Perform Action
    filter variables:
    - name: air_temperature
    action:
      name: assign error
      error function:
        name: ObsErrorModelStepwiseLinear@ObsFunction
        options:
          xvar:
            name: ObsValue/surface_pressure
          xvals: [10000, 20000, 25000, 30000, 50000, 85000, 97500, 100000]   #Pressure (Pa), ascending order
          errors: [3.0, 2.0, 1.5, 1.5, 2.0, 2.5, 2.5, 3.0]
  #
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    action:
      name: assign error
      error function:
        name: ObsErrorModelStepwiseLinear@ObsFunction
        options:
          xvar:
            name: ObsValue/surface_pressure
          xvals: [100000, 95000, 80000, 65000, 60000, 55000, 50000, 45000, 40000, 35000, 30000, 25000, 20000, 15000, 10000]   #Pressure (Pa)
          errors: [1.4, 1.5, 1.6, 1.8, 1.9, 2.0, 2.1, 2.3, 2.6, 2.8, 3.0, 3.2, 2.7, 2.4, 2.1]
  #
  - filter: Perform Action
    filter variables:
    - name: specific_humidity
    action:
      name: assign error
      error function:
        name: ObsErrorModelStepwiseLinear@ObsFunction
        options:
          scale_factor_var: ObsValue/specific_humidity
          xvar:
            name: ObsValue/surface_pressure
          xvals: [110000, 105000, 100000, 95000, 90000, 85000, 80000, 75000, 70000, 65000, 60000, 55000,
                   50000, 45000, 40000, 35000, 30000, 25000, 20000, 15000, 10000, 7500, 5000, 4000, 3000]
          errors: [.19455, .19062, .18488, .17877, .17342, .16976, .16777, .16696, .16605, .16522, .16637, .17086,
                   .17791, .18492, .18996, .19294, .19447, .19597, .19748, .19866, .19941, .19979, .19994, .19999, .2]
  # Inflate ObsError as it is done with GSI
  - filter: Perform Action
    filter variables:
    - name: surface_pressure
    action:
      name: inflate error
      inflation variable:
        name: ObsErrorFactorSfcPressure@ObsFunction
        options:
          error_min: 100         # 1 mb
          error_max: 300         # 3 mb
    defer to post: true
  # Gross error check with (O - B) / ObsError greater than threshold.
  - filter: Background Check
    filter variables:
    - name: surface_pressure
    threshold: 3.6
    absolute threshold: 990.0
    action:
      name: reject
  #
  - filter: Background Check
    filter variables:
    - name: air_temperature
    threshold: 7.0
    absolute threshold: 9.0
    action:
      name: reject
  #
  - filter: Background Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    threshold: 6.0
    absolute threshold: 16.0
    action:
      name: reject
  #
  - filter: Background Check
    filter variables:
    - name: specific_humidity
    threshold: 8.0
    action:
      name: reject
