obs space:
  name: sfcship
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sfcship.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      overwrite: true
      obsfile: !ENV ${DATA}/diags/diag_sfcship_${CDATE}.nc4
  io pool:
    max pool size: 1
  simulated variables: [stationPressure, airTemperature, specificHumidity]
obs operator:
  name: Composite
  components:
    - name: VertInterp
      variables:
      - name: airTemperature
      - name: specificHumidity
    - name: SfcPCorrected
      variables:
      - name: stationPressure
      da_psfc_scheme: GSI
      geovar_sfc_geomz: surface_geometric_height
      geovar_geomz: geopotential_height
linear obs operator:
  name: Identity

obs filters:
  # Observation range sanity check
  - filter: Bounds Check
    filter variables:
    - name: stationPressure
    minvalue: 37499.0
    maxvalue: 106999.0
    action:
      name: reject
    filter variables:
    - name: airTemperature
    minvalue: 195.0
    maxvalue: 327.0
    action:
      name: reject
    filter variables:
    - name: specificHumidity
    minvalue: 0.0
    maxvalue: 0.03499
    action:
      name: reject

  # Gross error check with (O - B) / ObsError greater than threshold.
  - filter: Background Check
    filter variables:
    - name: stationPressure
    threshold: 3.6
    absolute threshold: 990.0
    action:
      name: reject
    defer to post: true
    filter variables:
    - name: airTemperature
    threshold: 7.0
    absolute threshold: 9.0
    action:
      name: reject
    defer to post: true

  # Reject all ObsType 183
  - filter: BlackList
    where:
    - variable:
        name: ObsType/stationPressure
      is_in: 183
