obs operator:
  name: CRTM
  Absorbers: [H2O,O3,CO2]
  obs options:
    Sensor_ID: ssmis_f17
    EndianType: little_endian
    CoefficientPath: $(CRTM_COEFF_DIR)/
obs space:
  name: ssmis_f17
  obsdatain:
    engine:
      type: H5File
      obsfile: $(OBS_DIR)/$(OBS_PREFIX)ssmis_f17.$(OBS_DATE).nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: $(DIAG_DIR)/diag_ssmis_f17_$(OBS_DATE).nc4
  simulated variables: [brightness_temperature]
  channels: 1-24
geovals:
  filename: ssmis_f17_geoval_$(OBS_DATE).nc4
obs bias:
  input file: $(BIAS_IN_DIR)/$(BIAS_PREFIX)ssmis_f17.satbias.$(BIAS_DATE).nc4
  output file: $(BIAS_OUT_DIR)/$(OBS_PREFIX)ssmis_f17.satbias.$(OBS_DATE).nc4
  variational bc:
    predictors:
    - name: constant
    - name: cloud_liquid_water
      sensor: SSMIS
      ch19h: 12
      ch19v: 13
      ch22v: 14
      ch37h: 15
      ch37v: 16
      ch91v: 17
      ch91h: 18
    - name: cosine_of_latitude_times_orbit_node
    - name: sine_of_latitude
    - name: lapse_rate
      order: 2
      tlapse: &ssmis_f17_tlapse $(BIAS_IN_DIR)/$(BIAS_PREFIX)ssmis_f17.tlapse.$(BIAS_DATE).txt
    - name: lapse_rate
      tlapse: *ssmis_f17_tlapse
    - name: emissivity
    - name: scan_angle
      var_name: scan_position
      order: 4
    - name: scan_angle
      var_name: scan_position
      order: 3
    - name: scan_angle
      var_name: scan_position
      order: 2
    - name: scan_angle
      var_name: scan_position
obs filters:
- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 1
  action:
    name: assign error
    error parameter: 1.5

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 2-5
  action:
    name: assign error
    error parameter: 0.5

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 6-7, 23-24
  action:
    name: assign error
    error parameter: 1

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 8-11, 15, 19-20
  action:
    name: assign error
    error parameter: 3

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 12
  action:
    name: assign error
    error parameter: 2.4

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 13
  action:
    name: assign error
    error parameter: 1.27

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 14
  action:
    name: assign error
    error parameter: 1.44

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 16
  action:
    name: assign error
    error parameter: 1.34

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 17
  action:
    name: assign error
    error parameter: 1.74

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 18
  action:
    name: assign error
    error parameter: 3.75

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 21
  action:
    name: assign error
    error parameter: 2

- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 22
  action:
    name: assign error
    error parameter: 6.4
#step1: Gross check (setuprad)
- filter: Background Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  threshold: 1.5
  action:
    name: reject
#step1: Gross check(qcmod)
- filter: Background Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  absolute threshold: 3.5
  remove bias correction: true
  action:
    name: reject
- filter: Difference Check
  filter variables:
  - name: brightness_temperature
    channels: 1-2,12-16
  reference: brightness_temperature_2@ObsValue
  value: brightness_temperature_2@HofX
  minvalue: -1.5
  maxvalue: 1.5
  where:
  - variable:
      name: water_area_fraction@GeoVaLs
    maxvalue: 0.99
#QC_terrain: If seviri and terrain height > 2km. do not use
- filter: Domain Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  where:
    - variable:
        name: height_above_mean_sea_level@MetaData
      maxvalue: 2000.0
#do not use over mixed surface
- filter: BlackList
  filter variables:
  - name: brightness_temperature
    channels: 1-3,8-18
  where:
  - variable:
      name: land_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: water_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: ice_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: surface_snow_area_fraction@GeoVaLs
    maxvalue: 0.99
#step4: Generate q.c. bounds and modified variances
- filter: BlackList
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  action:
    name: inflate error
    inflation variable:
#  Surface Jacobian check
      name: ObsErrorFactorSurfJacobianRad@ObsFunction
      channels: 1-24
      options:
        channels: 1-24
        sensor: ssmis_f17
        obserr_demisf: [0.010, 0.010, 0.010, 0.010, 0.010]
        obserr_dtempf: [0.500, 0.500, 0.500, 0.500, 0.500]
#  Useflag Check
- filter: Bounds Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  test variables:
  - name: ChannelUseflagCheckRad@ObsFunction
    channels: 1-24
    options:
      channels: 1-24
      use_flag: [ 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1]
  minvalue: 1.0e-12
  action:
    name: reject
passedBenchmark: 440   #(m_unittest)