obs operator:
  name: CRTM
  Absorbers: [H2O,O3,CO2]
  obs options:
    Sensor_ID: ssmis_f18
    EndianType: little_endian
    CoefficientPath: $(CRTM_COEFF_DIR)/
obs space:
  name: ssmis_f18
  obsdatain:
    engine:
      type: H5File
      obsfile: $(OBS_DIR)/$(OBS_PREFIX)ssmis_f18.$(OBS_DATE).nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: $(DIAG_DIR)/diag_ssmis_f18_$(OBS_DATE).nc4
  simulated variables: [brightness_temperature]
  channels: 1-24
obs bias:
  input file: $(BIAS_IN_DIR)/$(BIAS_PREFIX)ssmis_f18.satbias.$(BIAS_DATE).nc4
  output file: $(BIAS_OUT_DIR)/$(OBS_PREFIX)ssmis_f18.satbias.$(OBS_DATE).nc4
  variational bc:
    predictors:
    - name: constant
    - name: cloud_liquid_water
      sensor: SSMIS
      ch19h: 12
      ch19v: 13
      ch22v: 14
      ch37h: 15
      ch37v: 16
      ch91v: 17
      ch91h: 18
    - name: cosine_of_latitude_times_orbit_node
    - name: sine_of_latitude
    - name: lapse_rate
      order: 2
      tlapse: &ssmis_f18_tlapse $(BIAS_IN_DIR)/$(BIAS_PREFIX)ssmis_f18.tlapse.$(BIAS_DATE).txt
    - name: lapse_rate
      tlapse: *ssmis_f18_tlapse
    - name: emissivity
    - name: scan_angle
      var_name: scan_position
      order: 4
    - name: scan_angle
      var_name: scan_position
      order: 3
    - name: scan_angle
      var_name: scan_position
      order: 2
    - name: scan_angle
      var_name: scan_position

obs prior filters:
- filter: Perform Action
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  action:
    name: assign error
    error parameter vector: [ 1.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 3, 3, 3, 3, 2.4, 1.27, 1.44, 3,
                1.34, 1.74, 3.75, 3, 3, 2, 6.4, 1, 1]

obs post filters:
#step1: Gross check (setuprad)
- filter: Background Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  threshold: 1.5
  action:
    name: reject
#step1: Gross check(qcmod)
- filter: Background Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  absolute threshold: 3.5
  remove bias correction: true
  action:
    name: reject

- filter: Difference Check
  filter variables:
  - name: brightness_temperature
    channels: 1-2,12-16
  reference: brightness_temperature_2@ObsValue
  value: brightness_temperature_2@HofX
  minvalue: -1.5
  maxvalue: 1.5
  where:
  - variable:
      name: water_area_fraction@GeoVaLs
    maxvalue: 0.99
#QC_terrain: If seviri and terrain height > 2km. do not use
- filter: Domain Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  where:
    - variable:
        name: height_above_mean_sea_level@MetaData
      maxvalue: 2000.0
#do not use over mixed surface
- filter: BlackList
  filter variables:
  - name: brightness_temperature
    channels: 1-3,8-18
  where:
  - variable:
      name: land_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: water_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: ice_area_fraction@GeoVaLs
    maxvalue: 0.99
  - variable:
      name: surface_snow_area_fraction@GeoVaLs
    maxvalue: 0.99
#step4: Generate q.c. bounds and modified variances
- filter: BlackList
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  action:
    name: inflate error
    inflation variable:
#  Surface Jacobian check
      name: ObsErrorFactorSurfJacobianRad@ObsFunction
      channels: 1-24
      options:
        channels: 1-24
        sensor: ssmis_f18
        obserr_demisf: [0.010, 0.010, 0.010, 0.010, 0.010]
        obserr_dtempf: [0.500, 0.500, 0.500, 0.500, 0.500]
#  Useflag Check
- filter: Bounds Check
  filter variables:
  - name: brightness_temperature
    channels: 1-24
  test variables:
  - name: ChannelUseflagCheckRad@ObsFunction
    channels: 1-24
    options:
      channels: 1-24
      use_flag: [ 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1]
  minvalue: 1.0e-12
  action:
    name: reject