#!/usr/bin/env python3
# genYAML
# generate YAML using ufsda python module,
# current runtime env, and optional input YAML
import argparse
import datetime as dt
import logging
import os
import re
import yaml

from ufsda.genYAML import genYAML

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', type=str, help='Input YAML Configuration', required=True)
    args = parser.parse_args()
    genYAML(args.config)
