obs space:
  name: adpsfc_snow
  distribution:
    name: Halo
    halo size: 250e3
  obsdatain:
    engine:
      type: H5File
      obsfile: $(DATA)/obs/$(OPREFIX)adpsfc_snow.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: $(DATA)/diags/diag_adpsfc_snow.nc4
  simulated variables: [totalSnowDepth]
obs operator:
  name: Composite
  components:
  - name: Identity
  - name: BackgroundErrorIdentity
obs error:
  covariance model: diagonal
obs localizations:
  - localization method: Horizontal SOAR
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 50
  - localization method: Vertical Brasnett
    vertical lengthscale: 700
obs pre filters:
  - filter: Perform Action
    filter variables:
    - name: totalSnowDepth
    action:
      name: assign error
      error parameter: 40.0
  - filter: Variable Assignment
    assignments:
    - name: GrossErrorProbability/totalSnowDepth
      type: float
      value: 0.02
    - name: BkgError/totalSnowDepth_background_error
      type: float
      value: 30.0
obs prior filters:
  - filter: Bounds Check
    filter variables:
    - name: totalSnowDepth
    minvalue: 0.0
    maxvalue: 2000.0
    action:
      name: reject
  - filter: Domain Check
    where:
    - variable:
        name: MetaData/height
      minvalue: -999.0
  - filter: Domain Check # land only
    where:
    - variable:
        name: GeoVaLs/slmsk
      minvalue: 0.5
      maxvalue: 1.5
  - filter: RejectList  # no land-ice
    where:
    - variable:
        name: GeoVaLs/vtype
      minvalue: 14.5
      maxvalue: 15.5
  - filter: BlackList
    where:
    - variable:
        name: MetaData/stationIdentification
      is_in: [71120,71397,71621,71727,71816]
      size where true: 5
obs post filters:
  - filter: Background Check # gross error check
    filter variables:
    - name: totalSnowDepth
    threshold: 6.25
    action:
      name: reject
  - filter: Temporal Thinning
    min_spacing: '{{ LAND_WINDOW_LENGTH }}'
    seed_time: '{{ current_cycle | to_isotime }}'
    category_variable:
      name: MetaData/stationIdentification
  - filter: Met Office Buddy Check
    filter variables:
    - name: totalSnowDepth
      rejection_threshold: 0.5
      traced_boxes: # trace all observations
        min_latitude: -90
        max_latitude:  90
        min_longitude: -180
        max_longitude:  180
      search_radius: 150 # km
      station_id_variable:
        name: MetaData/stationIdentification
      num_zonal_bands: 24
      sort_by_pressure: false
      max_total_num_buddies: 15
      max_num_buddies_from_single_band: 10
      max_num_buddies_with_same_station_id: 5
      use_legacy_buddy_collector: false
      horizontal_correlation_scale: { "-90": 150, "90": 150 }
      temporal_correlation_scale: PT6H
      damping_factor_1: 1.0
      damping_factor_2: 1.0
      background_error_group: BkgError

