obs space:
  name: ghcn_snow
  distribution:
    name: Halo
    simulated variables: [totalSnowDepth]
  obsdatain:
    obsfile: $(OBS_DIR)/$(OBS_PREFIX)ghcn_snow.$(OBS_DATE).nc4
  obsdataout:
    obsfile: $(DIAG_DIR)/diag_ghcn_snow_$(OBS_DATE).nc4

obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs localizations:
  - localization method: Horizontal SOAR
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 50
  - localization method: Vertical Brasnett
    vertical lengthscale: 700
obs filters:
  - filter: Bounds Check
    filter variables:
    - name: totalSnowDepth
    minvalue: 0.0
  - filter: Domain Check
    where:
    - variable:
        name: height@MetaData
      minvalue: -999.0
  - filter: Domain Check # land only
    where:
    - variable:
        name: slmsk@GeoVaLs
      minvalue: 0.5
      maxvalue: 1.5
  - filter: RejectList  # no land-ice
    where:
    - variable:
        name: vtype@GeoVaLs
      minvalue: 14.5
      maxvalue: 15.5
  - filter: Background Check
    filter variables:
    - name: totalSnowDepth
    threshold: 6.25
    action:
      name: reject
