obs space:
  name: ims_snow
  distribution:
    name: Halo
    halo size: 250e3
  obsdatain:
    obsfile: $(OBS_DIR)/$(OBS_PREFIX)ims_snow.$(OBS_DATE).nc4
  obsdataout:
    obsfile: $(DIAG_DIR)/diag_ims_snow_$(OBS_DATE).nc4
  io pool:
    max pool size: 1
  simulated variables: [totalSnowDepth]
get values:
  interpolation method: $(INTERP_METHOD)
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs localizations:
  - localization method: Horizontal SOAR
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 1
obs filters:
  - filter: Bounds Check
    filter variables:
    - name: totalSnowDepth
    minvalue: 0.0
  - filter: Domain Check # land only
    where:
    - variable:
        name: slmsk@GeoVaLs
      minvalue: 0.5
      maxvalue: 1.5
  - filter: RejectList  # no land-ice
    where:
    - variable:
        name: vtype@GeoVaLs
      minvalue: 14.5
      maxvalue: 15.5
  - filter: Background Check # gross error check
    filter variables:
    - name: totalSnowDepth
    threshold: 6.25
    action:
      name: reject

