obs space:
  name: ims_snow
  distribution:
    name: Halo
    halo size: 250e3
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}ims_snow_${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/diag_ims_snow_${CDATE}.nc4
  simulated variables: [totalSnowDepth]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs localizations:
  - localization method: Horizontal SOAR
    lengthscale: 250e3
    soar horizontal decay: 0.000021
    max nobs: 1
obs filters:
  - filter: Bounds Check
    filter variables:
    - name: totalSnowDepth
    minvalue: 0.0
  - filter: Domain Check # land only
    where:
    - variable:
        name: slmsk@GeoVaLs
      minvalue: 0.5
      maxvalue: 1.5
  - filter: RejectList  # no land-ice
    where:
    - variable:
        name: vtype@GeoVaLs
      minvalue: 14.5
      maxvalue: 15.5
  - filter: Background Check # gross error check
    filter variables:
    - name: totalSnowDepth
    threshold: 6.25
    action:
      name: reject

