# sample configuration with S3 being the archive,
# a local cache is created on disk. A local database
# can also be used.
# This file will be read in this location once installed (using
# python setup.py install).
# If you want to modify this file should be copied either into:
# - ~/.r2d2
# - /etc/r2d2
# and modified.

# list of databases we want to manage on the system
databases:
  # each key is the name of a database as known as the database
  # keyword in Fetch and Store. This is an arbitrary name.
  # Each entry has:
  # - class: required, the name of the Python class registered
  #   with the DBManager
  # - cache_fetch: optional. Set to True if a fetch on that
  #   database should be cached locally
  # - the other keywords are database dependent please refer to
  #   the R2D2 documentation.
  local:
    class: LocalDB
    root: /work2/noaa/da/${USER}/R2D2
    cache_fetch: false

  ufo_eval_ref:
    class: LocalDB
    root: /work/noaa/stmp/cmartin/UFO_eval_gfs/R2D2_readonly
    cache_fetch: false

  ufsda_test:
    class: LocalDB
    root: /work2/noaa/da/cmartin/R2D2
    cache_fetch: false

# when fetching data, in which order should the databases accessed?
fetch_order:
  - ufsda_test
  - ufo_eval_ref
  - local

# when storing data, in which order should the databases accessed?
store_order:
  - local

# name here which database in the list is the cache. Please note that
# the cache can be a local database that is used for other things
# (e.g. archiving fields locally and temporarily)
cache_name: local

# How the user wants the date formatted with in the filenames
# this option can be overridden in fetch and store
user_date_format: '%Y-%m-%dT%H:%M:%SZ'
