obs space:
  name: adt_j3
  obsdatain:
    obsfile: ./obs/adt_j3.{{window_begin}}.nc4
  obsdataout:
    obsfile: obs_out/adt_j3.{{window_begin}}.nc4
  simulated variables: [absolute_dynamic_topography]
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
