obs space:
  name: adt_j3
  obsdatain:
    obsfile: $(experiment_dir)/{{current_cycle}}/adt_j3.{{window_begin}}.nc4
  obsdataout:
    obsfile: $(experiment_dir)/{{current_cycle}}/$(experiment).adt_j3.{{window_begin}}.nc4
  simulated variables: [absolute_dynamic_topography]
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
