obs space:
  name: adt_rads_all
  obsdatain:
    engine:
      type: H5File
      obsfile: ${DATA}/obs/${OPREFIX}adt_rads_all.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DATA}/diags/adt_rads_all.${PDY}${cyc}.nc4
  simulated variables: [absoluteDynamicTopography]
  io pool:
    max pool size: 1
get values:
  time interpolation: linear
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
obs localizations:
- localization method: Rossby
  base value: 100.0e3
  rossby mult: 1.0
  min grid mult: 2.0
  min value: 200.0e3
  max value: 900.0e3
obs filters:
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    minvalue: 0.9
- filter: Domain Check
  where:
  - variable: { name: GeoVaLs/sea_surface_temperature}
    minvalue: 5.0
- filter: Background Check
  absolute threshold: 1.0
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_floor_depth_below_sea_surface}
    minvalue: 500
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables: [GeoVaLs/mesoscale_representation_error,
                    ObsError/absoluteDynamicTopography]
        coefs: [0.1,
                1.0]
- filter: Domain Check
  where:
  - variable: { name: GeoVaLs/sea_ice_area_fraction}
    maxvalue: 0.00001
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/distance_from_coast}
    minvalue: 100e3
