obs space:
  name: adt_coperl4
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${COM_OBS}/${OPREFIX}adt_coperl4.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/adt_coperl4.${PDY}${cyc}.nc4
  simulated variables: [absoluteDynamicTopography]
  io pool:
    max pool size: 1
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    minvalue: 0.9
# Reject obs where ocean fraction is < 90%
- filter: Domain Check
  action:
    name: reject
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    minvalue: 0.9
# Passivate obs where ocean fraction is > 90%
- filter: Domain Check
  action:
    name: passivate
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    maxvalue: 0.9
# Reject obs outside of [-4.0m,4.0m]
- filter: Bounds Check
  action:
    name: reject
  minvalue: -4.0
  maxvalue: 4.0
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/distance_from_coast}
    minvalue: 100e3
