obs space:
  name: adt_j3
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}adt_j3.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/adt_j3.${OBS_DATE}.nc4
  simulated variables: [absolute_dynamic_topography]
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
