obs space:
  name: adt_j3
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}adt_j3.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/adt_j3.${PDY}${cyc}.nc4
  simulated variables: [absolute_dynamic_topography]
obs operator:
  name: ADT
obs error:
  covariance model: diagonal
