obs space:
  name: adt_j3_egm2008
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}adt_j3_egm2008.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/adt_j3_egm2008.${PDY}${cyc}.nc4
  simulated variables: [absoluteDynamicTopography]
  io pool:
    max pool size: 1
obs operator:
  name: ADT
obs error:
  covariance model: diagonal

