obs space:
  name: bufr_sfcships
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}bufr_sfcships.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/bufr_sfcships.${CDATE}.nc4
  simulated variables: [sea_surface_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
