obs space:
  name: bufr_sfcshipsu
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}bufr_sfcshipsu.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/bufr_sfcshipsu.${OBS_DATE}.nc4
  simulated variables: [sea_surface_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
