obs space:
  name: icec_emc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}icec_emc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/icec_emc.${PDY}${cyc}.nc4
  simulated variables: [sea_ice_area_fraction]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
