obs space:
  name: icec_emc
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}icec_emc.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/icec_emc.${OBS_DATE}.nc4
  simulated variables: [sea_ice_area_fraction]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
