obs space:
  name: icec_nsidc_sh
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}icec_nsidc_sh.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/icec_nsidc_sh.${OBS_DATE}.nc4
  simulated variables: [sea_ice_area_fraction]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
_letkf: &letkf
  # note, this is only used for LETKF. If running with LETKF, the workflow
  # will append "<< : *letkf" to the end of this file
  obs localizations:
  - localization method: Horizontal Gaspari-Cohn
    lengthscale: 200e3
obs filters:
- filter: Bounds Check
  minvalue: 0.0
  maxvalue: 1.0
- filter: Background Check
  threshold: 5.0
- filter: Domain Check
  where:
  - variable: { name: sea_surface_temperature@GeoVaLs}
    maxvalue: 0.9
