- obs space:
    name: icec_ssmis_f17_south
    distribution:
      name: *obs_distribution
    obsdatain:
      engine:
        type: H5File
        obsfile: $(experiment_dir)/{{current_cycle}}/icec_ssmis_f17_south.{{window_begin}}.nc4
    obsdataout:
      engine:
        type: H5File
        obsfile: $(experiment_dir)/{{current_cycle}}/$(experiment).icec_ssmis_f17_south.{{window_begin}}.nc4
    simulated variables: [sea_ice_area_fraction]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: 0.0
    maxvalue: 1.0
  - filter: Background Check
    threshold: 5.0
  - filter: Domain Check
    where:
    - variable: { name: sea_surface_temperature@GeoVaLs}
      maxvalue: 2.0
  - filter: Domain Check
    where:
    - variable: { name: sea_surface_temperature@GeoVaLs}
      maxvalue: 0.0
    action:
      name: inflate error
      inflation factor: 2.0
  - filter: Domain Check
    where:
    - variable: {name: distance_from_coast@GeoVaLs}
      minvalue: 100e3

