obs space:
  name: icec_emc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${COM_OBS}/${OPREFIX}icec_emc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/icec_emc.${PDY}${cyc}.nc4
  simulated variables: [seaIceFraction]
obs operator:
  name: Identity
  observation alias file: ./obsop_name_map.yaml
obs error:
  covariance model: diagonal
