obs space:
  name: icefb_gdr
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}icefb_gdr.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/icefb_gdr.${OBS_DATE}.nc4
  simulated variables: [sea_ice_freeboard]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
