obs space:
  name: icefb_GDR
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}icefb_gdr.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/icefb_gdr.${PDY}${cyc}.nc4
  simulated variables:  [sea_ice_freeboard]
  io pool:
    max pool size: 1
get values:
  time interpolation: linear
obs operator:
  name: SeaIceThickness
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
- filter: Bounds Check
  minvalue: -0.1
  maxvalue: 1.0
- filter: Domain Check
  where:
  - variable: { name: sea_surface_temperature@GeoVaLs}
    maxvalue: -0.5
- filter: Background Check
  threshold: 3.0
- filter: Domain Check
  filter variables:
  - name: sea_ice_freeboard
  where:
  - variable:
      name: sea_ice_category_thickness@GeoVaLs
    minvalue: 0.5
    maxvalue: 5.0
