obs space:
  name: insitu_profile_bathy
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_profile_bathy.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_profile_bathy.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature, salinity]
  observed variables: [waterTemperature, salinity]
  io pool:
    max pool size: 1
obs operator:
  name: Composite
  components:
  - name: InsituTemperature
    variables:
    - name: waterTemperature
#  - name: VertInterp
#    observation alias file: ./obsop_name_map.yaml
#    - name: salinity
#    vertical coordinate: sea_water_depth
#    observation vertical coordinate: depth
#    interpolation method: linear
obs error:
  covariance model: diagonal
obs filters:
  # Passivate obs where ocean fraction is > 90%
  - filter: Domain Check
    action:
      name: passivate
    where:
    - variable: {name: GeoVaLs/sea_area_fraction}
      maxvalue: 0.9

