obs space:
  name: insitu_surface_trkob
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_surface_trkob.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_surface_trkob.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Identity
  observation alias file: obsop_name_map.yaml
obs error:
  covariance model: diagonal
