obs space:
  name: insitu_profile_tesac
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_profile_tesac.${PDY}${cyc}.nc
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_profile_tesac.${PDY}${cyc}.nc
  simulated variables: [waterTemperature]
  observed variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Composite
  components:
  - name: InsituTemperature
    variables:
    - name: waterTemperature
