obs space:
  name: insitu_profile_bathy
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_profile_bathy.${PDY}${cyc}.nc
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_profile_bathy.${PDY}${cyc}.nc
  simulated variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: InsituTemperature
obs error:
  covariance model: diagonal
