obs space:
  name: salt_profile_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}salt_profile_fnmoc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/salt_profile_fnmoc.${PDY}${cyc}.nc4
  simulated variables: [sea_water_salinity]
obs operator:
  name: MarineVertInterp
obs error:
  covariance model: diagonal
