obs space:
  name: salt_profile_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}salt_profile_fnmoc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/salt_profile_fnmoc.${PDY}${cyc}.nc4
  simulated variables: [salinity]
  io pool:
    max pool size: 1
obs operator:
  name: VertInterp
  observation alias file: ./obsop_name_map.yaml
  vertical coordinate: sea_water_depth
  observation vertical coordinate: depth
  interpolation method: linear
obs error:
  covariance model: diagonal
