obs space:
  name: insitu_s_profile_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}salt_profile_fnmoc.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/salt_profile_fnmoc.${OBS_DATE}.nc4
  simulated variables: [sea_water_salinity]
obs operator:
  name: MarineVertInterp
obs error:
  covariance model: diagonal
_letkf: &letkf
  # note, this is only used for LETKF. If running with LETKF, the workflow
  # will append "<< : *letkf" to the end of this file
  obs localizations:
  - localization method: Horizontal Gaspari-Cohn
    lengthscale: 500e3
obs filters:
- filter: Domain Check
  where:
  - variable: {name: sea_water_salinity@ObsError}
    minvalue: 0.0001
- filter: Bounds Check
  minvalue: 1.0
  maxvalue: 40.0
- filter: Background Check
  threshold: 2.0
# Measurement errors are too small, inflate almost everywhere
#- filter: Background Check
#  threshold: 0.01
#  action:
#    name: inflate error
#    inflation factor: 30.0
- filter: Domain Check
  where:
  - variable: {name: sea_surface_temperature@GeoVaLs}
    minvalue: 3.0
- filter: Domain Check
  where:
  - variable: { name: sea_ice_area_fraction@GeoVaLs}
    maxvalue: 0.00001
- filter: Domain Check
  where:
  - variable: {name: distance_from_coast@GeoVaLs}
    minvalue: 100e3
