obs space:
  name: salt_profile_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}salt_profile_fnmoc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/salt_profile_fnmoc.${PDY}${cyc}.nc4
  simulated variables: [salinity]
obs operator:
  name: MarineVertInterp
  observation alias file: ./obsop_name_map.yaml
obs error:
  covariance model: diagonal
