obs space:
  name: salt_bufr_dbuoyprof
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${COM_OBS}/${OPREFIX}salt_bufr_dbuoyprof.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/salt_bufr_dbuoyprof.${PDY}${cyc}.nc4
  simulated variables: [sea_water_salinity]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
