obs space:
  name: salt_bufr_mbuoybprof
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}salt_bufr_mbuoybprof.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/salt_bufr_mbuoybprof.${CDATE}.nc4
  simulated variables: [sea_water_salinity]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
