obs space:
  name: sss_smap
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${COM_OBS}/${OPREFIX}sss_smap.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/sss_smap.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceSalinity]
obs operator:
  name: Identity
  observation alias file: ./obsop_name_map.yaml
obs error:
  covariance model: diagonal
