obs space:
  name: sss_smap_jpl  
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}sss_smap_jpl.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/sss_smap_jpl.${OBS_DATE}.nc4
  simulated variables: [sea_surface_salinity]
  io pool:
    max pool size: 1
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
- filter: Bounds Check
  minvalue: 0.1
  maxvalue: 40.0
- filter: Background Check
  threshold: 5.0
- filter: Domain Check
  action:
    name: reject
  where:
  - variable: {name: sea_surface_salinity@ObsError}
    maxvalue: 0.6
- filter: Domain Check
  action:
    name: passivate
  where:
  - variable: {name: sea_surface_temperature@GeoVaLs}
    minvalue: 10.0
- filter: Domain Check
  where:
  - variable: {name: distance_from_coast@GeoVaLs}
    minvalue: 100e3
