obs space:
  name: sss_smap
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sss_smap.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/sss_smap.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceSalinity]
  io pool:
    max pool size: 1
get values:
  time interpolation: linear
obs operator:
  name: Identity
  observation alias file: ./obsop_name_map.yaml
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    minvalue: 0.9
- filter: Bounds Check
  minvalue: 0.0
  maxvalue: 41.0
- filter: Background Check
  absolute threshold: 1.0
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_surface_temperature}
    minvalue: 15.0
