obs space:
  name: sss_smap
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sss_smap.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/sss_smap.${CDATE}.nc4
  simulated variables: [sea_surface_salinity]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
