obs space:
  name: sst_viirs_npp_l3u_so025
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sst_viirs_npp_l3u_so025.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/sst_viirs_npp_l3u_so025.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Identity
  observation alias file: obsop_name_map.yaml
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_area_fraction}
    minvalue: 0.9
- filter: Bounds Check
  minvalue: 1.0
  maxvalue: 41.0
- filter: Background Check
  threshold: 5.0
- filter: Domain Check
  where:
  - variable: {name: ObsError/seaSurfaceTemperature}
    minvalue: 1.0e-8
- filter: Domain Check
  where:
  - variable: { name: GeoVaLs/sea_ice_area_fraction}
    maxvalue: 1.0e-5
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/sea_surface_temperature}
    minvalue: -1.0
- filter: Domain Check
  where:
  - variable: {name: GeoVaLs/distance_from_coast}
    minvalue: 100e3
