obs space:
  name: sst_windsat_l3u
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}sst_windsat_l3u.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/sst_windsat_l3u.${PDY}${cyc}.nc4
  simulated variables: [sea_surface_temperature]
  io pool:
    max pool size: 1
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
- filter: Bounds Check
  minvalue: -2.0
  maxvalue: 36.0
- filter: Background Check
  threshold: 5.0
- filter: Domain Check
  where:
  - variable: {name: sea_surface_temperature@ObsError}
    minvalue: 0.001
# Make all MW sst passive for now
- filter: Domain Check
  action:
    name: passivate
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    maxvalue: 0.9
- filter: Domain Check
  where:
  - variable: {name: distance_from_coast@GeoVaLs}
    minvalue: 100e3
