- obs space:
    name: sst_ostia
    distribution:
      name: *obs_distribution
    obsdatain:
      engine:
        type: H5File
        obsfile: $(experiment_dir)/{{current_cycle}}/sst_ostia.{{window_begin}}.nc4
    obsdataout:
      engine:
        type: H5File
        obsfile: $(experiment_dir)/{{current_cycle}}/$(experiment).sst_ostia.{{window_begin}}.nc4
    simulated variables: [sea_surface_temperature]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
  _letkf: &letkf
    # note, this is only used for LETKF. If running with LETKF, the workflow
    # will append "<< : *letkf" to the end of this file
    obs localizations:
    - localization method: Horizontal Gaspari-Cohn
      lengthscale: 200e3
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: -2.0
    maxvalue: 36.0
  - filter: Background Check
    threshold: 5.0
  - filter: Domain Check
    where:
    - variable: {name: sea_surface_temperature@ObsError}
      minvalue: 0.001
  - filter: Domain Check
    where:
    - variable: { name: sea_ice_area_fraction@GeoVaLs}
      maxvalue: 0.00001
  - filter: Domain Check
    where:
    - variable: {name: distance_from_coast@GeoVaLs}
      minvalue: 100e3
