obs space:
  name: sst_trak_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: ${OBS_DIR}/${OBS_PREFIX}sst_trak_fnmoc.${OBS_DATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DIAG_DIR}/sst_trak_fnmoc.${OBS_DATE}.nc4
  simulated variables: [sea_surface_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  action:
    name: reject
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
# Passivate obs where ocean fraction is > 90%
- filter: Domain Check
  action:
    name: passivate
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    maxvalue: 0.9
# Reject obs outside of [-2.0C,36.0C]
- filter: Bounds Check
  action:
    name: reject
  minvalue: -2.0
  maxvalue: 36.0
- filter: Domain Check
  where:
  - variable: {name: distance_from_coast@GeoVaLs}
    minvalue: 100e3
