obs space:
  name: temp_profile_fnmoc
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}temp_profile_fnmoc.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/temp_profile_fnmoc.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: InsituTemperature
obs error:
  covariance model: diagonal
