obs space:
  name: insitu_t_profile_wod
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}temp_profile_wod.${CDATE}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/temp_profile_wod.${CDATE}.nc4
  simulated variables: [sea_water_temperature]
  io pool:
    max pool size: 1
obs operator:
  name: InsituTemperature
obs error:
  covariance model: diagonal
obs filters:
- filter: Domain Check
  where:
  - variable: {name: sea_area_fraction@GeoVaLs}
    minvalue: 0.9
- filter: Domain Check
  where:
  - variable: {name: sea_water_temperature@ObsError}
    minvalue: 0.001
- filter: Bounds Check
  minvalue: -2.0
  maxvalue: 36.0
- filter: Background Check
  threshold: 3.0
# Measurement errors are too small, inflate almost everywhere
#- filter: Background Check
#  threshold: 0.01
#  action:
#    name: inflate error
#    inflation factor: 30.0
- filter: Domain Check
  where:
  - variable: { name: sea_ice_area_fraction@GeoVaLs}
    maxvalue: 0.00001
- filter: Domain Check
  where:
  - variable: {name: sea_surface_temperature@GeoVaLs}
    minvalue: 3.0
