obs space:
  name: temp_bufr_mbuoybprof
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}temp_bufr_mbuoybprof.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/temp_bufr_mbuoybprof.${PDY}${cyc}.nc4
  simulated variables: [sea_water_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
