obs space:
  name: bufr_sfcshipsu
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}bufr_sfcshipsu.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/bufr_sfcshipsu.${PDY}${cyc}.nc4
  simulated variables: [sea_surface_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
