name: Coding Norms
on: [push]

jobs:
  check_pynorms:
    runs-on: ubuntu-22.04
    name: Check coding norms with pycodestyle and cpplint

    steps:

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pycodestyle
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: GDASApp

    - name: Run pycodestyle
      run: |
        cd $GITHUB_WORKSPACE/GDASApp
        pycodestyle -v --config ./.pycodestyle ./ush ./scripts ./test 

    - name: Run C++ linter on utils 
      run: |
        cd $GITHUB_WORKSPACE/GDASApp/utils/test/
        ./cpplint.py --quiet --recursive --exclude=$GITHUB_WORKSPACE/GDASApp/utils/obsproc/rtofs/*.cc $GITHUB_WORKSPACE/GDASApp/utils
