name: Orion
on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Passes on Orion

    steps:

    - name: Passed 
      if: ${{ github.event.label.name == 'orion-RT-Passed' }}
      run: |
        echo "RT Passed on NOAA RDHPCS Orion"
    - name: Echo fail 
      if: ${{ github.event.label.name == 'orion-RT-Failed' }}
      run: |
        echo "RT failed on NOAA RDHPCS Orion"
        exit 1
    - name: Echo fail due to queued 
      if: ${{ github.event.label.name == 'orion-RT' }}
      run: |
        echo "RT queued on NOAA RDHPCS Orion"
        exit 1
    - name: Echo fail due to running 
      if: ${{ github.event.label.name == 'orion-RT-running' }}
      run: |
        echo "RT running on NOAA RDHPCS Orion"
        exit 1
