name: Testing on Orion
on:
  pull_request:
    types: [labeled]

jobs:
  testpass:
    if: ${{ github.event.label.name == 'orion-RT-Passed' }}
    runs-on: ubuntu-latest
    name: Passes on Orion

    steps:

    - name: Echo success 
      run: |
        echo "RT Passed on NOAA RDHPCS Orion"
  testfails:
    if: ${{ github.event.label.name == 'orion-RT-Failed' }}
    runs-on: ubuntu-latest
    name: Failed on Orion

    steps:

    - name: Echo fail 
      run: |
        echo "RT failed on NOAA RDHPCS Orion"
        exit 1
