name: Run Unit Tests
on: [pull_request]

jobs:
  ctests:
    runs-on: ubuntu-latest
    name: Run Unit Tests with ctest

    steps:

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pycodestyle
        pip install netCDF4

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: GDASApp

    - name: Cache ecBuild
      id: cache-ecbuild
      uses: actions/cache@v2
      with:
        path: ecbuild
        key: ${{ runner.os }}-ecbuild

    - name: Install ecBuild
      if: steps.cache-ecbuild.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/ecmwf/ecbuild.git ecbuild
        cd ecbuild
        git checkout 3.6.1

    - name: Configure with cmake
      run: |
        mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_GDASBUNDLE=OFF $GITHUB_WORKSPACE/GDASApp

    - name: Build GDASApp
      run: |
        cd $GITHUB_WORKSPACE/build
        make

    - name: Run ctest
      run: |
        cd $GITHUB_WORKSPACE/build
        ctest --output-on-failure

