name: Unit Tests
on: [push, pull_request]

jobs:
  ctests:
    runs-on: ubuntu-latest
    name: Run Unit Tests with ctest

    steps:

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install pycodestyle
        pip install netCDF4
        pip install xarray

    - name: Install other dependencies
      run: |
        wget https://ftp.emc.ncep.noaa.gov/static_files/public/GDASApp/r2d2-bb361c2.tar.gz
        wget https://ftp.emc.ncep.noaa.gov/static_files/public/GDASApp/solo-877b414.tar.gz
        tar -xvf r2d2-bb361c2.tar.gz
        tar -xvf solo-877b414.tar.gz
        cd solo && pip install . && cd ..
        cd r2d2 && pip install . && cd ..

    - name: Checkout workflow
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/global-workflow
        ref: develop
        path: global-workflow

    - name: Install workflow utils
      run: |
        cd global-workflow/ush/python
        pip install .

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: GDASApp

    - name: Install ecBuild
      run: |
        git clone https://github.com/ecmwf/ecbuild.git ecbuild
        cd ecbuild
        git checkout 3.6.1
        mkdir bootstrap
        cd bootstrap
        ../bin/ecbuild ..
        sudo make install

    - name: Configure with cmake
      run: |
        mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_GDASBUNDLE=OFF $GITHUB_WORKSPACE/GDASApp

    - name: Build GDASApp
      run: |
        cd $GITHUB_WORKSPACE/build
        make

    - name: Run ctest
      run: |
        cd $GITHUB_WORKSPACE/build
        ctest --output-on-failure
