name: Run Unit Tests
on: [push, pull_request]

jobs:
  ctests:
    runs-on: ubuntu-latest
    name: Run Unit Tests with ctest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: GDASapp

    - name: Configure with cmake
      run: |
        cd $GITHUB_WORKSPACE/GDASapp
        mkdir build
        cd build
        cmake ../

    - name: Build GDASapp
      run: |
        cd $GITHUB_WORKSPACE/GDASapp/build
        make

    - name: Run ctest
      run: |
        cd $GITHUB_WORKSPACE/GDASapp/build
        ctest
